String response1 =
"HTTP/1.1 200 OK\n"
"Content-type:text/html\n"
"\n"
"<!DOCTYPE HTML>"
"<html>"
        "<head>"
                "<link href='https://fonts.googleapis.com/css?family=Barlow Regular' rel='stylesheet'>"
                "<style TYPE=\"text/css\">"
                        "TABLE{"
                                "border-radius:10px;"
                        "}"
                        "TD{"
                                "font-family: 'Barlow Regular';"
                                "font-size: 15pt;"
                                "font-weight: bold;"
                        "}"
                        "t1{"
                                "font-family: 'Barlow Regular';"
                                "color: #FFFFFF;"
                                "font-size: 30pt;"
                                "font-weight: bold;"
                        "}  "
                        "t2{"
                                "font-family: 'Barlow Regular';"
                                "color: #FFFFFF;"
                                "font-size: 20pt;"
                                "text-align: center;"
                        "}       "
                        "li{"
                                "font-family: 'Barlow Regular';"
                                "color: #FFFFFF;"
                                "font-size: 25pt;"
                                "font-weight: bold;"
                        "}     "
                        "form{"
                                "font-family: 'Barlow Regular';"
                                "color: #FFFFFF;"
                                "font-size: 20pt;"
                        "}    "
                        "tab{"
                                "margin-left: 30px;"
                        "}"
                        "input{"
                                "font-family: 'Barlow Regular';"
                                "color: #FF3376;"
                                "font-size: 20pt;"
                                "font-weight: bold;"
                        "}"
                        "button{"
                                "font-family: 'Barlow Regular';"
                                "font-size: 15pt;"
                                "font-weight: bold;"
                                "color: #FFCE1A;"
                        "}"
                        "t3{"
                                "font-family: 'Barlow Regular';"
                                "color: #FFFFFF;"
                                "font-size: 20pt;"
                        "}"
                        "input.defaultCheckbox {"
                                "width: 20px;" 
                                "height: 20px;" 
                        "}"
                "</style>"
                "<title>Kineis KIM1 interface shield</title>"
                "<meta charset= \"utf-8\">"
        "</head>"
        "<body style=\"background-color:#002028;\">"
                "<t1>Kineis KIM1 interface shield :</t1>"
                "<ul>"
                        "<form>"
                                "<div>"
                                "<input type=\"submit\" style=\"float: right;\" name=\"REFRESH\" value=\"REFRESH\">"
                                "</div>"
                        "</form>"
                        "<table width=\"100%\" border=\"1\" cellspacing=\"4\" cellpadding=\"5\" width=\"200\" align=\"left\" bgcolor=\"#FF3376\">"
                                "<li>Module :</li>"
                                "<tr bgcolor=\"#FFCE1A\">"
                                        "<td width=\"20%\">ID</td>"
                                        "<td>";
String response2 =
                                        "</td>"
                                "</tr>"
                                "<tr bgcolor=\"#FFCE1A\">"
                                        "<td>SN</td>"
                                        "<td>";
String response3 =
                                "</td>"
                                "</tr>"
                                "<tr bgcolor=\"#FFCE1A\">"
                                        "<td>FW</td>"
                                        "<td>";
String response4 =
                                "</td>"
                                "</tr>"
                                "<tr bgcolor=\"#FFCE1A\">"
                                        "<td>PWR</td>"
                                        "<td>";
String response5 =
                                "</td>"
                                "</tr>"
                                "<tr bgcolor=\"#FFCE1A\">"
                                        "<td>BAND</td>"
                                        "<td>";
String response6 =
                                "</td>"
                                "</tr>"
                                "<tr bgcolor=\"#FFCE1A\">"
                                        "<td>TCXOWU (hex)</td>"
                                        "<td>";
String response7 =
                                "</td>"
                                "</tr>"
                                "<tr bgcolor=\"#FFCE1A\">"
                                        "<td>FRQ</td>"
                                        "<td>";
String response8 =
                                "</td>"
                                "</tr>"
                                "<tr bgcolor=\"#FFCE1A\">"
                                        "<td>TRANSMISSION PERIOD (s)</td>"
                                        "<td>";
String response9 =
                                "</td>"
                                "</tr>"
                        "</table>"
                        "<li>Set value :</li>"
                        "<form>"
                                "<div>"
                                        "<input type=\"checkbox\" class=\"defaultCheckbox\" id=\"ID\" name=\"ID\" value=\"setID\">"
                                        "<label for=\"ID\">ID</label>"
                                        
                                        "<input type=\"checkbox\" class=\"defaultCheckbox\" id=\"SN\" name=\"SN\" value=\"setSN\">"
                                        "<label for=\"SN\">SN</label>"
                                        
                                        "<input type=\"checkbox\" class=\"defaultCheckbox\" id=\"FW\" name=\"FW\" value=\"setFW\">"
                                        "<label for=\"FW\">FW</label>"
                                        
                                        "<input type=\"checkbox\" class=\"defaultCheckbox\" id=\"PWR\" name=\"PWR\" value=\"setPWR\">"
                                        "<label for=\"PWR\">PWR</label>"
                                        
                                        "<input type=\"checkbox\" class=\"defaultCheckbox\" id=\"BAND\" name=\"BAND\" value=\"setBAND\">"
                                        "<label for=\"BAND\">BAND</label>"
                                        
                                        "<input type=\"checkbox\" class=\"defaultCheckbox\" id=\"TCXOWU\" name=\"TCXOWU\" value=\"setTCXOWU\">"
                                        "<label for=\"TCXOWU\">TCXOWU</label>"
                                        
                                        "<input type=\"checkbox\" class=\"defaultCheckbox\" id=\"FRQ\" name=\"FRQ\" value=\"setFRQ\">"
                                        "<label for=\"FRQ\">FRQ</label>"
                                        
                                        "<input type=\"checkbox\" class=\"defaultCheckbox\" id=\"T_TR\" name=\"T_TR\" value=\"setT_TR\">"
                                        "<label for=\"T_TR\">TRANSMISSION PERIOD</label>"
                                "</div>"
                                "<div>"
                                "<input type=\"text\" id=\"ucommand\" name=\"SET\" placeholder=\"...\" size=\"60\">"
                                "<input type=\"submit\" value=\"SET\">"
                                "</div>"
                        "</form>"
                        
                        "<li>Send payload :</li>"
                        "<form>"
                                "<div>"
                                        "<input type=\"text\" id=\"ucommand\" name=\"SEND\" placeholder=\"Payload\" size=\"60\">"
                                        "<input type=\"submit\" value=\"SEND\">"
                                "</div>"
                                "<div><t3>"
                                        "<input type=\"checkbox\" class=\"defaultCheckbox\" id=\"TR_P\" name=\"TR_P\" value=\"TR_P\" checked>"
                                        "<label for=\"TR_P\">Periodic transmission</label>"
                                "</t3></div>"
                        "</form>"
                        "<li>KIM response :</li>"
                        "<div>"
                                "<t2>";
String response10 =
                                "</t2>"
                        "</div>"
                "</ul>"
        "</body>"
"</html>";
